---
title: "Example Workflow"
author: "TADA Team"
date: "2025-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get Montana TADA Data

Get data bacteria and pH data from Montana.

```{r tada.data}

# get Montna bacteria data 
tada.MT <- TADA_DataRetrieval(
   startDate = "2020-01-01", endDate = "2022-12-31",
   statecode = "MT",
   characteristicName = c("Escherichia", "Escherichia coli", "pH"),
   county = "Missoula County",
   ask = FALSE)

# clean up data set (minimal)
  tada.MT.clean <- tada.MT %>%
    TADA_RunKeyFlagFunctions() %>%
    TADA_SimpleCensoredMethods()
  
# remove intermediate objects
  rm(tada.MT)

```


## Set up Demo User-Supplied Crosswalk

Get existing data from ATTAINS

```{r demo.user, echo = FALSE}

# get crosswalk from ATTAINS
attains.existing.MT <- TADA_GetATTAINSAUSiteCrosswalk(org_id = "MTDEQ")

# clean existing crosswalk from ATTAINS to make sure monitoring location IDs are 
# WQP compatible
clean.existing.attains.MT <- TADA_UpdateMonitoringLocationsInATTAINS(org_id = "MTDEQ")

# set up demo user supplied cw (select a few Monitoring Locations from the tada df)
user.supplied.cw <- clean.existing.attains.MT %>%
  dplyr::select(ATTAINS.AssessmentUnitIdentifier, 
                ATTAINS.MonitoringLocationIdentifier) %>%
  dplyr::filter(ATTAINS.MonitoringLocationIdentifier %in% c(
    "MDEQ_WQ_WQX-C04CKFKR05", "MDEQ_WQ_WQX-C04KNDYC01", "MDEQ_WQ_WQX-C04KNDYC02", 
    "MDEQ_WQ_WQX-C04KNDYC04", "MDEQ_WQ_WQX-C04KNDYC54")) %>%
  dplyr::rename(AssessmentUnitIdentifier = ATTAINS.AssessmentUnitIdentifier,
                MonitoringLocationIdentifier = ATTAINS.MonitoringLocationIdentifier)

rm(attains.existing.MT, clean.existing.attains.MT)
```

## Run TADA_CreateAUMLRef

```{r tada.get.attains}

# use TADA get attains to make AU assignments for unassigned MLs
MT.AUMLRef <- TADA_CreateAUMLRef(tada.MT.clean,
                                 au_ref = user.supplied.cw,
                                 org_id = "MTDEQ", 
                                 add_catch = FALSE)

```
## TADA_ViewATTAINS
```{r}

TADA_ViewATTAINS(MT.AUMLRef)

```



