test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})

test_that("TADAdataRetrieval", {
  tada1 <- TADAdataRetrieval(siteid = c("USGS-054064785",
                                        "USGS-430305089260600"),
                             characteristicName = "Phosphorus")
  # you could just pick the important columns:
  expect_true(all(c("OrganizationIdentifier",                           
                    "OrganizationFormalName",                           
                    "ActivityIdentifier",                               
                    "ActivityTypeCode",                                 
                    "ActivityMediaName",                                
                    "ActivityMediaSubdivisionName",                     
                    "ActivityStartDate",                                
                    "ActivityStartTime.Time",                           
                    "ActivityStartTime.TimeZoneCode",                   
                    "ActivityEndDate",                                  
                    "ActivityEndTime.Time",                             
                    "ActivityEndTime.TimeZoneCode",                     
                    "ActivityDepthHeightMeasure.MeasureValue",          
                    "ActivityDepthHeightMeasure.MeasureUnitCode",       
                    "ActivityDepthAltitudeReferencePointText",          
                    "ActivityTopDepthHeightMeasure.MeasureValue",       
                    "ActivityTopDepthHeightMeasure.MeasureUnitCode",    
                    "ActivityBottomDepthHeightMeasure.MeasureValue",    
                    "ActivityBottomDepthHeightMeasure.MeasureUnitCode", 
                    "ProjectIdentifier",                                
                    "ActivityConductingOrganizationText",               
                    "MonitoringLocationIdentifier",                     
                    "ActivityCommentText",                              
                    "SampleAquifer",                                    
                    "HydrologicCondition",                              
                    "HydrologicEvent",                                  
                    "SampleCollectionMethod.MethodIdentifier",          
                    "SampleCollectionMethod.MethodIdentifierContext",   
                    "SampleCollectionMethod.MethodName",                
                    "SampleCollectionEquipmentName",                    
                    "ResultDetectionConditionText",                     
                    "CharacteristicName",                              
                    "ResultSampleFractionText",                         
                    "ResultMeasureValue",                               
                    "ResultMeasureValue.Original",                      
                    "TADA.ResultMeasureValue.Flag",                     
                    "ResultMeasure.MeasureUnitCode",                    
                    "MeasureQualifierCode",                             
                    "ResultStatusIdentifier",                           
                    "StatisticalBaseCode",                              
                    "ResultValueTypeName",                              
                    "ResultWeightBasisText",                            
                    "ResultTimeBasisText",                              
                    "ResultTemperatureBasisText",                       
                    "ResultParticleSizeBasisText" ,                     
                    "PrecisionValue",                                   
                    "ResultCommentText",                                
                    "USGSPCode",                                        
                    "ResultDepthHeightMeasure.MeasureValue",           
                    "ResultDepthHeightMeasure.MeasureUnitCode",         
                    "ResultDepthAltitudeReferencePointText",            
                    "SubjectTaxonomicName",                             
                    "SampleTissueAnatomyName",                          
                    "ResultAnalyticalMethod.MethodIdentifier",          
                    "ResultAnalyticalMethod.MethodIdentifierContext",   
                    "ResultAnalyticalMethod.MethodName",                
                    "MethodDescriptionText",                            
                    "LaboratoryName",                                   
                    "AnalysisStartDate" ,                               
                    "ResultLaboratoryCommentText",                      
                    "DetectionQuantitationLimitTypeName",               
                    "DetectionQuantitationLimitMeasure.MeasureValue",   
                    "DetectionLimitMeasureValue.Original",              
                    "TADA.DetectionLimitMeasureValue.Flag",             
                    "DetectionQuantitationLimitMeasure.MeasureUnitCode",
                    "PreparationStartDate",                             
                    "ProviderName",                                     
                    "ActivityStartDateTime",                            
                    "ActivityEndDateTime" ,                             
                    "MonitoringLocationName",                           
                    "MonitoringLocationTypeName",                       
                    "MonitoringLocationDescriptionText",                
                    "HUCEightDigitCode",                                
                    "DrainageAreaMeasure.MeasureValue",                 
                    "DrainageAreaMeasure.MeasureUnitCode",              
                    "ContributingDrainageAreaMeasure.MeasureValue",     
                    "ContributingDrainageAreaMeasure.MeasureUnitCode",  
                    "LatitudeMeasure",                                  
                    "LongitudeMeasure",                                 
                    "SourceMapScaleNumeric",                            
                    "HorizontalAccuracyMeasure.MeasureValue",           
                    "HorizontalAccuracyMeasure.MeasureUnitCode",        
                    "HorizontalCollectionMethodName",                   
                    "HorizontalCoordinateReferenceSystemDatumName",     
                    "VerticalMeasure.MeasureValue",                 
                    "VerticalMeasure.MeasureUnitCode",                 
                    "VerticalAccuracyMeasure.MeasureValue",             
                    "VerticalAccuracyMeasure.MeasureUnitCode",          
                    "VerticalCollectionMethodName",                     
                    "VerticalCoordinateReferenceSystemDatumName",      
                    "CountryCode",                                      
                    "StateCode",                                      
                    "CountyCode",                                     
                    "AquiferName",                                   
                    "LocalAqfrName",                               
                    "FormationTypeText",                                
                    "AquiferTypeName",                            
                    "ConstructionDateText",                   
                    "WellDepthMeasure.MeasureValue",                
                    "WellDepthMeasure.MeasureUnitCode",               
                    "WellHoleDepthMeasure.MeasureValue",           
                    "WellHoleDepthMeasure.MeasureUnitCode" ,            
                    "MethodSpecificationName") %in% names(tada1)))
  
})
