# Lists can be used within TADA_OrderCols, TADA_GetTemplate, TADA_CheckRequiredFields, TADA_AutoFilter, TADA_RetainRequired

# ordered list of TADA workflow required columns to be retained in data frame
require.cols <- c(
  # Comparable Data Groups (e.g. Observable Properties)
  "ResultSampleFractionText", # required in Module 1 but is replaced by TADA version in future modules
  "TADA.ResultSampleFractionText", # generated/required/replaces original
  "TADA.SampleFraction.Flag",
  "TADA.FractionAssumptions",
  "CharacteristicName", # required in Module 1 but is replaced by TADA version in future modules
  "TADA.CharacteristicName", # generated/required/replaces original
  "TADA.CharacteristicNameAssumptions", # generated
  "SubjectTaxonomicName",
  "SampleTissueAnatomyName",
  "MethodSpeciationName", # required in Module 1 but is replaced by TADA version in future modules
  "TADA.MethodSpeciationName", # generated/required/replaces original
  "TADA.MethodSpeciation.Flag", # generated
  "TADA.SpeciationAssumptions",
  "TADA.SpeciationConversionFactor",
  "TADA.ComparableDataIdentifier",
  "TADA.Harmonized.Flag",
  
  # Result Value
  "ResultMeasureValue", # required in Module 1 but is replaced by TADA version in future modules
  "TADA.ResultMeasureValue", # generated/required/replaces original
  "TADA.ResultMeasureValueDataTypes.Flag", # generated
  "ResultValueTypeName", # required
  "TADA.ResultValueAboveUpperThreshold.Flag",
  "TADA.ResultValueBelowLowerThreshold.Flag",
  
  # Result Unit
  "ResultMeasure.MeasureUnitCode", # required in Module 1 but is replaced by TADA version in future modules
  "TADA.ResultMeasure.MeasureUnitCode", # generated/required/replaces original
  "TADA.WQXResultUnitConversion", # generated, only added when transform = FALSE in TADA_ConvertResultUnits
  "TADA.WQXTargetUnit", # generated, only added when transform = FALSE in TADA_ConvertResultUnits
  "TADA.WQXUnitConversionFactor", # generated, only added when transform = FALSE in TADA_ConvertResultUnits
  "TADA.UnitConversionFactor", # generated, added from TADA harmonization template
  "TADA.SpeciationUnitConversion", # generated, only added when transform = FALSE in TADA_ConvertResultUnits
  "TADA.ResultUnit.Flag", # generated
  
  # Detection Limits
  "ResultDetectionConditionText", #required
  "DetectionQuantitationLimitTypeName",
  "DetectionQuantitationLimitMeasure.MeasureValue",
  "TADA.DetectionQuantitationLimitMeasure.MeasureValue",
  "TADA.DetectionQuantitationLimitMeasure.MeasureValueDataTypes.Flag",
  "DetectionQuantitationLimitMeasure.MeasureUnitCode",
  "TADA.DetectionQuantitationLimitMeasure.MeasureUnitCode",
  "TADA.CensoredData.Flag",
  "TADA.CensoredMethod",
  
  # Result Value Context
  "StatisticalBaseCode", # required
  "ResultFileUrl", # filter, may contain continuous data text file
  "TADA.AggregatedContinuousData.Flag", # generated
  "TADA.ResultValueAggregation.Flag", # generated, specifies if value is discrete or a daily max, avg, min
  "TADA.NutrientSummation.Flag", # generated
  "TADA.NutrientSummationGroup", # generated
  "TADA.NutrientSummationEquation", # generated
  
  # Sample/Measurement Collection/Analytical Method
  "ResultAnalyticalMethod.MethodName",
  "ResultAnalyticalMethod.MethodDescriptionText",
  "ResultAnalyticalMethod.MethodIdentifier",
  "ResultAnalyticalMethod.MethodIdentifierContext",
  "ResultAnalyticalMethod.MethodUrl",
  "TADA.AnalyticalMethod.Flag", 
  "SampleCollectionMethod.MethodIdentifier", # required
  "SampleCollectionMethod.MethodIdentifierContext", # required
  "SampleCollectionMethod.MethodName", # required
  "SampleCollectionMethod.MethodDescriptionText", # required
  "SampleCollectionEquipmentName", # required
  
  # Sample/Measurement Type (e.g. QC or Not)
  "ActivityTypeCode", # required
  
  # Media
  "ActivityMediaName", # required
  "TADA.ActivityMediaName", # generated/required/replaces original
  "ActivityMediaSubdivisionName", # filter
  
  # Result Time
  "ActivityStartDate", # required
  "ActivityStartTime.Time", # filter
  "ActivityStartTime.TimeZoneCode", # filter
  "ActivityStartDateTime", # required/generated by USGS DR
  "ResultTimeBasisText", # required
  
  # Result Depth
  "ResultDepthHeightMeasure.MeasureValue",
  "TADA.ResultDepthHeightMeasure.MeasureValue",
  "TADA.ResultDepthHeightMeasure.MeasureValueDataTypes.Flag",
  "ResultDepthHeightMeasure.MeasureUnitCode",
  "TADA.ResultDepthHeightMeasure.MeasureUnitCode",
  "TADA.WQXConversionFactor.ResultDepthHeightMeasure",
  "ResultDepthAltitudeReferencePointText",

  # Activity Depth
  "ActivityRelativeDepthName", # required
  "ActivityDepthHeightMeasure.MeasureValue", # required
  "TADA.WQXConversionFactor.ActivityDepthHeightMeasure",
  "TADA.ActivityDepthHeightMeasure.MeasureValue", # generated/required/replaces original
  "TADA.ActivityDepthHeightMeasure.MeasureValueDataTypes.Flag", # generated
  "ActivityDepthHeightMeasure.MeasureUnitCode", # required
  "TADA.ActivityDepthHeightMeasure.MeasureUnitCode", # generated/required/replaces original
  "ActivityTopDepthHeightMeasure.MeasureValue", # required
  "TADA.ActivityTopDepthHeightMeasure.MeasureValue", # generated/required/replaces original
  "TADA.WQXConversionFactor.ActivityTopDepthHeightMeasure",
  "TADA.ActivityTopDepthHeightMeasure.MeasureValueDataTypes.Flag", # generated
  "ActivityTopDepthHeightMeasure.MeasureUnitCode", # required
  "TADA.ActivityTopDepthHeightMeasure.MeasureUnitCode", # generated/required/replaces original
  "ActivityBottomDepthHeightMeasure.MeasureValue", # required
  "TADA.ActivityBottomDepthHeightMeasure.MeasureValue", # generated/required/replaces original
  "TADA.WQXConversionFactor.ActivityBottomDepthHeightMeasure",
  "TADA.ActivityBottomDepthHeightMeasure.MeasureValueDataTypes.Flag", # generated
  "ActivityBottomDepthHeightMeasure.MeasureUnitCode", # required
  "TADA.ActivityBottomDepthHeightMeasure.MeasureUnitCode", # generated/required/replaces original
  
  # Result Quality
  "MeasureQualifierCode", # required, could be replaced by TADA.MeasureQualifierCode.Def in future mods
  "TADA.MeasureQualifierCode.Flag", # generated
  "TADA.MeasureQualifierCode.Def", # generated, could replace MeasureQualifierCode in future mods
  "ResultCommentText",
  "ActivityCommentText", # required
  "HydrologicCondition", # filter, weather conditions
  "HydrologicEvent", # filter, weather conditions
  "DataQuality.PrecisionValue", # required
  "DataQuality.BiasValue", # required
  "DataQuality.ConfidenceIntervalValue", # required
  "DataQuality.UpperConfidenceLimitValue", # required
  "DataQuality.LowerConfidenceLimitValue", # required
  "SamplingDesignTypeCode",
  "LaboratoryName",
  "ResultLaboratoryCommentText",
  "ResultIdentifier", # required
  "ActivityIdentifier", # required
  
  # Organization (e.g. data submitter)
  "OrganizationIdentifier", # required
  "OrganizationFormalName", # required
  "TADA.MultipleOrgDuplicate",
  "TADA.MultipleOrgDupGroupID",
  "TADA.ResultSelectedMultipleOrgs",
  "TADA.SingleOrgDupGroupID",
  "TADA.SingleOrgDup.Flag",
  
  # Organization Projects
  "ProjectName", # required
  "ProjectDescriptionText",
  "ProjectIdentifier", # required
  "ProjectFileUrl", # required, may include QAPP doc
  "QAPPApprovedIndicator",
  "QAPPApprovalAgencyName",
  "TADA.QAPPDocAvailable", # generated, based on ProjectFileUrl
  
  # Organization Monitoring Locations
  "CountryCode",
  "StateCode",
  "CountyCode",
  "MonitoringLocationName", # required
  "MonitoringLocationTypeName",
  "MonitoringLocationDescriptionText",
  "LatitudeMeasure",
  "TADA.LatitudeMeasure", # generated
  "LongitudeMeasure",
  "TADA.LongitudeMeasure", # generated
  "TADA.InvalidCoordinates.Flag", # generated
  "HUCEightDigitCode",
  "MonitoringLocationIdentifier", # required 
  "TADA.NearbySiteGroups",
  
  # Groundwater fields
  "AquiferName", # filter, groundwater
  "AquiferTypeName", # filter
  "LocalAqfrName", # filter, groundwater
  "ConstructionDateText",  # filter
  "WellDepthMeasure.MeasureValue", # filter
  "WellDepthMeasure.MeasureUnitCode", # filter
  "WellHoleDepthMeasure.MeasureValue", # filter
  "WellHoleDepthMeasure.MeasureUnitCode", # filter
  
  "ProviderName", # filter
  "LastUpdated", # filter
  
  # Only used in TADA Shiny
  "TADA.Remove",
  "TADA.RemovalReason",
  "TADAShiny.tab"
)

# ordered list of non-essential columns that can be removed from df
extra.cols <- c(
  "ActivityDepthAltitudeReferencePointText",
  "ActivityEndDate",
  "ActivityEndTime.Time",
  "ActivityEndTime.TimeZoneCode",
  "ActivityEndDateTime", # generated by USGS DR
  "ActivityConductingOrganizationText",
  "SampleAquifer",
  "ActivityLocation.LatitudeMeasure",
  "ActivityLocation.LongitudeMeasure",
  "ResultStatusIdentifier",
  "ResultWeightBasisText",
  "ResultTemperatureBasisText",
  "ResultParticleSizeBasisText",
  "USGSPCode",
  "BinaryObjectFileName",
  "BinaryObjectFileTypeCode",
  "AnalysisStartDate",
  "ResultDetectionQuantitationLimitUrl",
  "LabSamplePreparationUrl",
  "timeZoneStart",
  "timeZoneEnd",
  "SourceMapScaleNumeric",
  "HorizontalAccuracyMeasure.MeasureValue",
  "HorizontalAccuracyMeasure.MeasureUnitCode",
  "HorizontalCollectionMethodName",
  "HorizontalCoordinateReferenceSystemDatumName",
  "VerticalMeasure.MeasureValue",
  "VerticalMeasure.MeasureUnitCode",
  "VerticalAccuracyMeasure.MeasureValue",
  "VerticalAccuracyMeasure.MeasureUnitCode",
  "VerticalCollectionMethodName",
  "VerticalCoordinateReferenceSystemDatumName",
  "FormationTypeText",
  "ProjectMonitoringLocationWeightingUrl",
  "DrainageAreaMeasure.MeasureValue",
  "DrainageAreaMeasure.MeasureUnitCode",
  "ContributingDrainageAreaMeasure.MeasureValue",
  "ContributingDrainageAreaMeasure.MeasureUnitCode"
)
