# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples

on:
  pull_request_target:

name: format-suggest.yaml

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Format
        run: air format . --check
        continue-on-error: true
        
      - name: Suggest
        uses: reviewdog/action-suggester@v1
        with:
          level: error
          fail_level: error
          tool_name: air
