name: Update Component Files

on:
  pull_request:
    branches:
      [develop]
  # Daily at 2:01AM https://crontab.guru/
  schedule:
    - cron: '1 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  maintenance_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Update reference files
        with:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages('remotes')
          remotes::install_github("USEPA/EPATADA", ref = "develop", dependencies = TRUE, force = TRUE)
          library(EPATADA)
          # ATTAINSRefTables.R
          EPATADA:::TADA_UpdateATTAINSOrgIDsRef()
          EPATADA:::TADA_UpdateATTAINSParamUseOrgRef() # takes a long time
          EPATADA:::TADA_UpdateATTAINSParameterWQPCharRef()
          # WQPWQXRefTables.R
          EPATADA:::TADA_UpdateWQXCharValRef()
          EPATADA:::TADA_UpdateMeasureUnitRef()
          EPATADA:::TADA_UpdateDetCondRef()
          EPATADA:::TADA_UpdateDetLimitRef()
          EPATADA:::TADA_UpdateActivityTypeRef()
          EPATADA:::TADA_UpdateCharacteristicRef()
          EPATADA:::TADA_UpdateMeasureQualifierCodeRef()
          EPATADA:::TADA_UpdateMonLocTypeRef()
          EPATADA:::TADA_UpdateWQPOrgProviderRef()
          # CriteriaRefTables.R
          EPATADA:::TADA_UpdateEPACSTRef()
          # TADAGeospatialRefLayers.R
          EPATADA:::TADA_UpdateTribalLayers()
        shell: Rscript {0}

      - name: Commit updated reference files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: "Update reference files"
          add: '[./inst/extdata/*]'
          
      - name: Update example data
        run: |
          library(EPATADA)
          TADA_UpdateExampleData <- function() {
            # Generate Data_Nutrients_UT
            Data_Nutrients_UT <- TADA_DataRetrieval(
              statecode = "UT",
              characteristicName = c("Ammonia", "Nitrate", "Nitrogen"),
              startDate = "2020-10-01",
              endDate = "2022-09-30",
              ask = FALSE
            )
            print("Data_Nutrients_UT")
            print(dim(Data_Nutrients_UT))
            usethis::use_data(Data_Nutrients_UT,
              internal = FALSE, overwrite = TRUE,
              compress = "xz", version = 3, ascii = FALSE
            )
            rm(Data_Nutrients_UT)
          
            # Generate Data_6Tribes_5y.rda
            Data_6Tribes_5y <- TADA_DataRetrieval(
              organization = c(
                "REDLAKE_WQX",
                "SFNOES_WQX",
                "PUEBLO_POJOAQUE",
                "FONDULAC_WQX",
                "PUEBLOOFTESUQUE",
                "CNENVSER"
              ),
              startDate = "2018-01-01",
              endDate = "2023-01-01",
              ask = FALSE
            )
            print("Data_6Tribes_5y:")
            print(dim(Data_6Tribes_5y))
            usethis::use_data(Data_6Tribes_5y,
              internal = FALSE, overwrite = TRUE,
              compress = "xz", version = 3, ascii = FALSE
            )
          
            # Generate Data_6Tribes_5y_Harmonized.rda
            y <- subset(Data_6Tribes_5y, Data_6Tribes_5y$TADA.ActivityMediaName %in% c("WATER"))
            y <- TADA_RunKeyFlagFunctions(Data_6Tribes_5y, clean = TRUE)
            rm(Data_6Tribes_5y)
            y <- TADA_FlagMethod(y, clean = TRUE)
            y <- TADA_FlagAboveThreshold(y, clean = TRUE)
            y <- TADA_FlagBelowThreshold(y, clean = TRUE)
            y <- TADA_FindPotentialDuplicatesMultipleOrgs(y, dist_buffer = 100)
            y <- TADA_FindPotentialDuplicatesSingleOrg(y)
            y <- dplyr::filter(y, !(MeasureQualifierCode %in% c("D", "H", "ICA", "*")))
            y <- TADA_SimpleCensoredMethods(y,
              nd_method = "multiplier",
              nd_multiplier = 0.5,
              od_method = "as-is",
              od_multiplier = "null"
            )
            y <- dplyr::filter(y, TADA.ResultMeasureValueDataTypes.Flag != "Text" &
              TADA.ResultMeasureValueDataTypes.Flag != "NA - Not Available" &
              !is.na(TADA.ResultMeasureValue))
            Data_6Tribes_5y_Harmonized <- TADA_HarmonizeSynonyms(y)
            print("Data_6Tribes_5y_Harmonized:")
            print(dim(Data_6Tribes_5y_Harmonized))
            usethis::use_data(Data_6Tribes_5y_Harmonized,
              internal = FALSE, overwrite = TRUE,
              compress = "xz", version = 3, ascii = FALSE
            )
            rm(Data_6Tribes_5y_Harmonized)
            rm(y)
          
            # # Generate Data_NCTCShepherdstown_HUC12

            # Generate Data_R5_TADAPackageDemo
            Data_R5_TADAPackageDemo <- TADA_DataRetrieval(
              startDate = "2019-05-01",
              endDate = "2019-05-07",
              countycode = "null",
              huc = "null",
              siteid = "null",
              siteType = "null",
              characteristicName = "null",
              characteristicType = "null",
              sampleMedia = "null",
              statecode = c("IL", "IN", "MI", "MN", "OH", "WI"),
              organization = "null",
              project = "null",
              applyautoclean = FALSE,
              ask = FALSE
            )
            print("Data_R5_TADAPackageDemo:")
            print(dim(Data_R5_TADAPackageDemo))
            usethis::use_data(Data_R5_TADAPackageDemo, internal = FALSE, overwrite = TRUE, compress = "xz", version = 3, ascii = FALSE)
            rm(Data_R5_TADAPackageDemo)
          
            # Generate MODULE 3 VIGNETTE EXAMPLE DATA
            # Get data
            Data_WV <- TADA_DataRetrieval(
              startDate = "2020-03-14",
              huc = "02070004",
              applyautoclean = FALSE,
              ask = FALSE
            )
            # Remove non-surface water media
            # OPTIONAL
            Data_WV <- TADA_AnalysisDataFilter(
              Data_WV,
              clean = TRUE,
              surface_water = TRUE,
              ground_water = FALSE,
              sediment = FALSE
            )
            # Remove single org duplicates
            # REQUIRED
            Data_WV <- TADA_FindPotentialDuplicatesSingleOrg(
              Data_WV
            )
            Data_WV <- dplyr::filter(
              Data_WV,
              TADA.SingleOrgDup.Flag == "Unique"
            )
            # Run autoclean
            # REQUIRED
            Data_WV <- TADA_AutoClean(Data_WV)
            # Prepare censored results
            # REQUIRED
            Data_WV <- TADA_SimpleCensoredMethods(
              Data_WV,
              nd_method = "multiplier",
              nd_multiplier = 0.5,
              od_method = "as-is",
              od_multiplier = "null"
            )
            # Remove multiple org duplicates
            # OPTIONAL
            Data_WV <- TADA_FindPotentialDuplicatesMultipleOrgs(
              Data_WV
            )
            Data_WV <- dplyr::filter(
              Data_WV,
              TADA.ResultSelectedMultipleOrgs == "Y"
            )
            # Filter out remaining irrelevant data, NA's and empty cols
            Data_WV <- TADA_ConvertSpecialChars(Data_WV,
              col = "TADA.ResultMeasureValue",
              clean = TRUE
            )
            # Remove results with QC issues
            # REQUIRED
            Data_WV <- TADA_RunKeyFlagFunctions(
              Data_WV,
              clean = TRUE
            )
            # Flag above and below threshold. Do not remove
            Data_WV <- TADA_FlagAboveThreshold(Data_WV, clean = FALSE, flaggedonly = FALSE)
            Data_WV <- TADA_FlagBelowThreshold(Data_WV, clean = FALSE, flaggedonly = FALSE)
            # Harmonize synonyms
            Data_WV <- TADA_HarmonizeSynonyms(Data_WV)
            # Save example data
            Data_HUC8_02070004_Mod1Output <- Data_WV
            print("Data_HUC8_02070004_Mod1Output:")
            print(dim(Data_HUC8_02070004_Mod1Output))
            usethis::use_data(Data_HUC8_02070004_Mod1Output,
              internal = FALSE,
              overwrite = TRUE,
              compress = "xz",
              version = 3,
              ascii = FALSE
            )
            rm(Data_HUC8_02070004_Mod1Output)
            rm(Data_WV)
          }
          TADA_UpdateExampleData()
        shell: Rscript {0}

      - name: Commit updated example data
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: "Update example data"
          add: '[./data/*]'
