
on:
  push:
    branches: [hrm_test]
  pull_request:
    branches: [hrm_test]

name: url-check

jobs:
  url-check:
    runs-on: ubuntu-latest
    # env:
    #   GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::urlchecker
        
      - name: Run URL Check
        run: |
          R -e "
          library(urlchecker)
 
          check <- urlchecker::url_check()

          if(nrow(check) > 0) {
 
          cat('The following URLs are broken:\n')
          cat(check$URL, sep = '\n')
          quit(status = 1)
   
          } else {
          cat('All URLs are valid.\n')
          } 
          "