# Workflow derived from https://github.com/technote-space/broken-link-checker-action
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  # release:
  #   types: [published]
  workflow_dispatch:

name: Broken Link Check

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages(c("xml2", "rvest", "httr"))

    - name: Run Broken Link Checker
      uses: technote-space/broken-link-checker-action@v2
      with:
        target: 'https://github.com/USEPA/EPATADA/'  # Replace with your package URL
        recursive: true