
on:
  push:
    branches: [hrm_test]
  pull_request:
    branches: [hrm_test]
  # release:
  #   types: [published]
  workflow_dispatch:

name: Check URLs

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
        name: Checkout repository
        uses: actions/checkout@v3

        name: Install dependencies
        run: apt-get update && install -y curl

        name: Find and check URLs
        run: |
          grep -Eo '(http|https)://[^/"]+' -r . | while read -r url; do
            if ! curl --output /dev/null --silent --head --fail "$url"; then
              echo "Broken URL: $url"
              exit 1
            fi
          done